/**
 * Azure DevOps data layer for weekly reports.
 *
 * Fetches PRs and commits across all configured repos for a given week window.
 * Detects AI-tool signatures (Claude / Codex / Cursor) from PR descriptions.
 *
 * Auth:
 *   1. AZURE_TOKEN env var (preferred)
 *   2. azureDevOps.pat in Dr.-Nexus/config.json
 *
 * If neither is available the section is skipped gracefully.
 */

import https from 'node:https';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '../..');

// ── Token resolution (mirrors Dr.-Nexus/src/service/azure.js) ─────────────────

/**
 * Resolve the Azure DevOps PAT.
 * Priority: AZURE_TOKEN env → az.pat in config → tokenCommand (e.g. _ado_token via zsh).
 */
function resolveToken(az) {
  if (process.env.AZURE_TOKEN) return process.env.AZURE_TOKEN;
  if (az.pat) return az.pat;

  const tokenCommand = az.tokenCommand;
  if (!tokenCommand) return null;

  try {
    const shellParts = [];
    if (az.sourceZshrc) shellParts.push('source ~/.zshrc >/dev/null 2>&1');
    shellParts.push(tokenCommand);

    const token = execFileSync('/bin/zsh', ['-lc', shellParts.join('\n')], {
      stdio: 'pipe',
      timeout: 15000,
      encoding: 'utf-8',
    }).trim();

    return token || null;
  } catch (e) {
    const detail = (e.stderr?.toString() || e.message || '').slice(0, 120);
    console.warn(`  [azure] Token command failed: ${detail}`);
    return null;
  }
}

// ── Config ─────────────────────────────────────────────────────────────────────

function loadConfig() {
  const p = resolve(ROOT, 'nexus-agent/config.json');
  try {
    const raw = JSON.parse(readFileSync(p, 'utf-8'));
    const az = raw.azureDevOps || {};

    // org may be stored as full URL or just the name
    const orgRaw = az.org || '';
    const org = orgRaw.startsWith('http')
      ? orgRaw.replace(/^https?:\/\/dev\.azure\.com\//, '').replace(/\/$/, '')
      : orgRaw;

    const pat = resolveToken(az);

    return {
      org,
      project: az.project || '',
      pat,
      authorName: 'Amar',
      authorEmail: 'amargupta@gofynd.com',
      repos: Object.entries(raw.services || {}).map(([key, svc]) => ({
        key,
        repo: svc.repo || key,
      })),
    };
  } catch (e) {
    throw new Error(`Cannot read nexus-agent/config.json: ${e.message}`);
  }
}

// ── HTTP helpers ───────────────────────────────────────────────────────────────

function get(url, headers) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers }, (res) => {
      let data = '';
      res.on('data', c => (data += c));
      res.on('end', () => {
        const status = res.statusCode || 0;
        if (status >= 400) {
          return reject(new Error(`HTTP ${status} ${url.slice(0, 120)}\n${data.slice(0, 300)}`));
        }
        try { resolve(data ? JSON.parse(data) : {}); }
        catch (e) { reject(new Error(`JSON parse error: ${e.message}`)); }
      });
      res.on('error', reject);
    });
  });
}

async function paginate(url, headers, key = 'value') {
  const all = [];
  let skip = 0;
  const top = 100;
  while (true) {
    const sep = url.includes('?') ? '&' : '?';
    const res = await get(`${url}${sep}$top=${top}&$skip=${skip}`, headers);
    const items = res[key] || [];
    all.push(...items);
    if (items.length < top) break;
    skip += top;
  }
  return all;
}

// ── AI detection ───────────────────────────────────────────────────────────────

const AI_PATTERNS = [
  { re: /made-with:\s*cursor/i,                    tool: 'Cursor' },
  { re: /co-authored-by:.*cursor/i,                tool: 'Cursor' },
  { re: /generated with \[?claude/i,               tool: 'Claude' },
  { re: /co-authored-by:.*claude/i,                tool: 'Claude' },
  { re: /🤖\s*generated with/i,                    tool: 'Claude' },
  { re: /auto-generated by \[?nexus/i,             tool: 'Claude' }, // Dr.-Nexus new footer
  { re: /_auto-generated by nexus_/i,              tool: 'Claude' }, // Dr.-Nexus old footer
  { re: /pr-agent\s+cli/i,                         tool: 'Claude' }, // pr-agent (Claude-powered)
  { re: /ai:\s*codex/i,                            tool: 'Codex'  }, // pr-agent with Codex
  { re: /co-authored-by:.*codex/i,                 tool: 'Codex'  },
  { re: /\bcodex\b/i,                              tool: 'Codex'  },
  { re: /openai/i,                                 tool: 'Codex'  },
  { re: /\bgpt[-\s]?\d/i,                         tool: 'Codex'  },
];

function detectAiTool(text = '', title = '') {
  for (const { re, tool } of AI_PATTERNS) {
    if (re.test(text)) return tool;
  }

  // Fallback for historical pr-agent PRs where the description was truncated by the
  // Azure list API before the footer was visible.
  // pr-agent titles use the pattern: [JCP-NNNNN] ... or ID:JCP-NNNNN; ...
  // AND the description contains a markdown table with Source/Target branches —
  // both are unique to pr-agent output.
  const hasPrAgentTitle = /^\[JCP-\d+\]|^ID:JCP-\d+/i.test((title || '').trim());
  const hasPrAgentTable = /\|\s*\*\*Source\*\*\s*\|/i.test(text);
  if (hasPrAgentTitle && hasPrAgentTable) return 'Claude';

  return null;
}

// ── Per-repo fetchers ──────────────────────────────────────────────────────────

async function fetchRepoPRs(repoBase, repo, headers, fromISO, toISO) {
  try {
    // Fetch all PRs created in the window (all statuses)
    const url = `${repoBase}/pullrequests?api-version=7.0`
      + `&searchCriteria.status=all`
      + `&searchCriteria.queryTimeRangeType=created`
      + `&searchCriteria.minTime=${fromISO}`
      + `&searchCriteria.maxTime=${toISO}`;
    return await paginate(url, headers);
  } catch (e) {
    console.warn(`  [azure] PRs ${repo}: ${e.message.slice(0, 100)}`);
    return [];
  }
}

async function fetchRepoCommits(repoBase, repo, headers, authorName, fromISO, toISO) {
  try {
    const url = `${repoBase}/commits?api-version=7.0`
      + `&searchCriteria.author=${encodeURIComponent(authorName)}`
      + `&searchCriteria.fromDate=${fromISO}`
      + `&searchCriteria.toDate=${toISO}`;
    return await paginate(url, headers);
  } catch (e) {
    console.warn(`  [azure] Commits ${repo}: ${e.message.slice(0, 100)}`);
    return [];
  }
}

// ── Main export ────────────────────────────────────────────────────────────────

/**
 * Fetch Azure DevOps PRs and commits for the given week.
 *
 * @param {Date} fromDate
 * @param {Date} toDate
 * @returns {Promise<AzureWeekData>}
 */
export async function fetchWeeklyAzureData(fromDate, toDate) {
  let cfg;
  try {
    cfg = loadConfig();
  } catch (e) {
    return { skipped: true, reason: e.message, prs: [], commits: [], repos: [], summary: emptySummary() };
  }

  if (!cfg.pat) {
    return {
      skipped: true,
      reason: 'Azure token unavailable. Set AZURE_TOKEN env var, or ensure _ado_token is accessible via zsh.',
      prs: [], commits: [], repos: [], summary: emptySummary(),
    };
  }

  const headers = {
    Authorization: `Basic ${Buffer.from(`:${cfg.pat}`).toString('base64')}`,
    'Content-Type': 'application/json',
  };

  const baseUrl = `https://dev.azure.com/${encodeURIComponent(cfg.org)}`
    + `/${encodeURIComponent(cfg.project)}/_apis/git/repositories`;

  const fromISO = fromDate.toISOString();
  const toISO   = toDate.toISOString();

  const allPRs     = [];
  const allCommits = [];

  for (const { key, repo } of cfg.repos) {
    const repoBase = `${baseUrl}/${encodeURIComponent(repo)}`;

    const [rawPRs, rawCommits] = await Promise.all([
      fetchRepoPRs(repoBase, repo, headers, fromISO, toISO),
      fetchRepoCommits(repoBase, repo, headers, cfg.authorName, fromISO, toISO),
    ]);

    // Filter PRs to only the current user's PRs (author name contains "Amar")
    const myPRs = rawPRs.filter(pr =>
      (pr.createdBy?.displayName || '').toLowerCase().includes(cfg.authorName.toLowerCase())
    );

    for (const pr of myPRs) {
      const text = pr.description || '';
      const aiTool = detectAiTool(text, pr.title || '');
      allPRs.push({
        repo,
        serviceKey: key,
        prId: pr.pullRequestId,
        title: pr.title || '',
        author: pr.createdBy?.displayName || '',
        status: pr.status,          // active | completed | abandoned
        createdDate: pr.creationDate?.slice(0, 10) || null,
        mergedDate: pr.closedDate?.slice(0, 10) || null,
        aiTool,
        url: `https://dev.azure.com/${cfg.org}/${cfg.project}/_git/${repo}/pullrequest/${pr.pullRequestId}`,
      });
    }

    for (const c of rawCommits) {
      // Skip auto-generated merge commits — they inflate the count without
      // representing actual code changes.  Merge commits are identified by the
      // two Azure DevOps auto-message prefixes.
      const msg = (c.comment || '').trim();
      const isMergeCommit = msg.startsWith('Merge pull request ') || msg.startsWith('Merged PR ');
      if (isMergeCommit) continue;

      const isCursor = /made-with:\s*cursor/i.test(msg);
      allCommits.push({
        repo,
        serviceKey: key,
        commitId: (c.commitId || '').slice(0, 8),
        author: c.author?.name || '',
        date: c.author?.date?.slice(0, 10) || null,
        message: msg.split('\n')[0].slice(0, 120),
        isCursor,
      });
    }
  }

  // Exclude abandoned PRs from AI-assist rate — they were discarded, not shipped.
  const activePRs    = allPRs.filter(p => p.status !== 'abandoned');
  const mergedPRs    = allPRs.filter(p => p.status === 'completed');
  // AI assist: only count active + merged PRs (not abandoned drafts)
  const aiPRs        = activePRs.filter(p => p.aiTool !== null);
  const cursorCommits = allCommits.filter(c => c.isCursor);

  // Breakdown by AI tool
  const byTool = {};
  for (const pr of aiPRs) {
    byTool[pr.aiTool] = (byTool[pr.aiTool] || 0) + 1;
  }

  // Commits per day (for activity chart)
  const commitsByDay = {};
  for (const c of allCommits) {
    if (c.date) commitsByDay[c.date] = (commitsByDay[c.date] || 0) + 1;
  }

  // Commits per repo
  const commitsByRepo = {};
  for (const c of allCommits) {
    commitsByRepo[c.repo] = (commitsByRepo[c.repo] || 0) + 1;
  }

  return {
    skipped: false,
    prs: activePRs,         // active + merged only (abandoned excluded from report)
    mergedPRs,
    commits: allCommits,    // real code commits (merge commits stripped)
    cursorCommits,
    aiPRs,
    byTool,
    commitsByDay,
    commitsByRepo,
    repos: cfg.repos.map(r => r.repo),
    summary: {
      totalPRs: activePRs.length,
      mergedPRs: mergedPRs.length,
      activePRs: activePRs.filter(p => p.status === 'active').length,
      totalCommits: allCommits.length,
      cursorCommits: cursorCommits.length,
      aiPRs: aiPRs.length,
      aiAssistRate: activePRs.length > 0
        ? Math.round((aiPRs.length / activePRs.length) * 100)
        : 0,
    },
  };
}

function emptySummary() {
  return { totalPRs: 0, mergedPRs: 0, activePRs: 0, totalCommits: 0, cursorCommits: 0, aiPRs: 0, aiAssistRate: 0 };
}
